/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        ElButton: typeof import('element-plus/es')['ElButton'];
        ElCol: typeof import('element-plus/es')['ElCol'];
        ElContainer: typeof import('element-plus/es')['ElContainer'];
        ElForm: typeof import('element-plus/es')['ElForm'];
        ElFormItem: typeof import('element-plus/es')['ElFormItem'];
        ElHeader: typeof import('element-plus/es')['ElHeader'];
        ElInput: typeof import('element-plus/es')['ElInput'];
        ElMain: typeof import('element-plus/es')['ElMain'];
        ElRow: typeof import('element-plus/es')['ElRow'];
        ElTable: typeof import('element-plus/es')['ElTable'];
        ElTableColumn: typeof import('element-plus/es')['ElTableColumn'];
        Home: typeof import('./components/Home/index.vue')['default'];
        Icons: typeof import('./components/common/icons.vue')['default'];
        NavMenu: typeof import('./components/Home/NavMenu.vue')['default'];
        NotFound: typeof import('./components/NotFound.vue')['default'];
        RouterLink: typeof import('vue-router')['RouterLink'];
        RouterView: typeof import('vue-router')['RouterView'];
    }
}
